### ISSUE TITLE
Make /admin/ page mobile friendly

### ISSUE THREAD

**Issue by AdrianAndersen** [abakus-ntnu/charitystream#34]
Currently, the admin page looks pretty thrash on mobile. Should make some sort of hamburger menu when on mobile to make it look nicer. Also, a lot of UI should be improved to make it look nicer.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/26925695/198074872-ceeb55b7-67fe-4678-a8d6-4413b32b9ca1.png">

**Comment by norbye** [comment]
More or less resolved in #44
